services:
  - type: web
    name: playcontrol-backend
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/roles
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: FACEBOOK_APP_ID
        sync: false
      - key: FACEBOOK_APP_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: APP_PUBLIC_URL
        value: https://playcontrol-backend.onrender.com
      - key: APP_FRONTEND_URL
        value: https://playcontrol-upc.web.app
