spring.application.name=tp
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/bdTP
spring.datasource.username=postgres
spring.datasource.password=2108

server.port=8080
