package com.example.tp.entities;
import jakarta.persistence.*;

@Entity
@Table(name = "Challenge")
public class Challenge {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    @Column(name = "title", length = 200, nullable = false)
    private String title;

    @Column(name = "description", length = 200)
    private String description;

    @Column(name = "type", length = 20, nullable = false)
    private String type;

    @Column(name = "durationDays", nullable = false)
    private int durationDays;

    @Column(name = "autoGenerated", nullable = false)
    private boolean autoGenerated;

    @Column(name = "targetUserId")
    private int targetUserId;

    @Column(name = "achievementId")
    private int achievementId;

    public Challenge() {
    }

    public Challenge(int id, String title, String description, String type, int durationDays, boolean autoGenerated, int targetUserId, int achievementId) {
        this.id = id;
        this.title = title;
        this.description = description;
        this.type = type;
        this.durationDays = durationDays;
        this.autoGenerated = autoGenerated;
        this.targetUserId = targetUserId;
        this.achievementId = achievementId;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public int getDurationDays() {
        return durationDays;
    }

    public void setDurationDays(int durationDays) {
        this.durationDays = durationDays;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    public int getTargetUserId() {
        return targetUserId;
    }

    public void setTargetUserId(int targetUserId) {
        this.targetUserId = targetUserId;
    }

    public int getAchievementId() {
        return achievementId;
    }

    public void setAchievementId(int achievementId) {
        this.achievementId = achievementId;
    }
}
